/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.RemoteApp
{
    public class KillRoverResponse : Message
    {
        public const string RosMessageName = "remote_app/KillRover";

        public string err { get; set; }

        public KillRoverResponse()
        {
            this.err = "";
        }

        public KillRoverResponse(string err)
        {
            this.err = err;
        }
    }
}
