/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.RemoteApp
{
    public class PollRoverResponse : Message
    {
        public const string RosMessageName = "remote_app/PollRover";

        public bool alive { get; set; }
        public string err { get; set; }

        public PollRoverResponse()
        {
            this.alive = false;
            this.err = "";
        }

        public PollRoverResponse(bool alive, string err)
        {
            this.alive = alive;
            this.err = err;
        }
    }
}
