/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.RemoteApp
{
    public class PollRoverRequest : Message
    {
        public const string RosMessageName = "remote_app/PollRover";

        public string machine_name { get; set; }

        public PollRoverRequest()
        {
            this.machine_name = "";
        }

        public PollRoverRequest(string machine_name)
        {
            this.machine_name = machine_name;
        }
    }
}
