/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Jaybot
{
    public class SetSpeedRequest : Message
    {
        public const string RosMessageName = "jaybot/SetSpeed";

        public byte spd_pct { get; set; }

        public SetSpeedRequest()
        {
            this.spd_pct = 0;
        }

        public SetSpeedRequest(byte spd_pct)
        {
            this.spd_pct = spd_pct;
        }
    }
}
